
[package]
name = "ups"
version = "0.1.0"
edition = "2018"

[dependencies]
lettre = "0.10.0-rc.4"
hidapi = "1.3.0"
serde = { version = "1.0.130", features = ["derive"] }
figment = { version = "0.10.6", features = ["toml"] }
